### ISSUE TITLE
Unable to open ./models/shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by roshanverma8652** [anubhavshrimal/FaceRecognition#10]
Hello,
thanks for the tutorial 
Currently I am facing an Run time error 

Traceback (most recent call last):
  File "c:\Users\Roshan\Desktop\Omkar\Face-Recognition-master\create_encodings.py", line 2, in <module>    
    import face_recognition_api
  File "c:\Users\Roshan\Desktop\Omkar\Face-Recognition-master\face_recognition_api.py", line 8, in <module>
    pose_predictor = dlib.shape_predictor(predictor_model)
RuntimeError: Unable to open ./models/shape_predictor_68_face_landmarks.dat

Could you plzz help me with this ?

**Comment by SilverHound27** [comment]
Move the 'shape_predictor_68_face_landmarks.dat' from /models to root of the project.
