### ISSUE TITLE
Getting error in predict.py and webcam.py

### ISSUE THREAD

**Issue by mouazzamj1** [anubhavshrimal/FaceRecognition#8]
Getting the following error:
```
Traceback (most recent call last):
  File "predict.py", line 54, in <module>
    zip(clf.predict(faces_encodings), X_faces_loc, is_recognized)]
  File "predict.py", line 53, in <listcomp>
    predictions = [(le.inverse_transform(int(pred)).title(), loc) if rec else ("Unknown", loc) for pred, loc, rec in
  File "/home/pwc/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "/home/pwc/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 797, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape () 
```

This error is in predict.py as well as webcam.py. I saw you have closed this bug posted by others. Please reply on how to fix this.

**Comment by kishor1210** [comment]
Replace (le.inverse_transform(int(pred)).title() ------------> (le.inverse_transform([int(pred)]).[0] in both predict.py and webcam.py.
